 CREATE TABLE USER_ROLES (
    USER_ROLE_NUM  NUMBER(20) NOT NULL,
    USERNUM       VARCHAR(50) NOT NULL,
    USERID      VARCHAR(20) NOT NULL,
    ROLE          VARCHAR(45) NOT NULL,
    PRIMARY KEY (USER_ROLE_NUM),
    CONSTRAINT  FK_USERNUM FOREIGN KEY (USERNUM) 
    REFERENCES  USER_TBL (NUM)
);

CREATE SEQUENCE USER_ROLES_SEQ
    START     WITH 1
    INCREMENT BY 1
    MAXVALUE  99999999
    NOCYCLE; 
    
INSERT INTO USER_ROLES (USER_ROLE_NUM, USERNUM, USERID, ROLE) 
VALUES (
            USER_ROLES_SEQ.NEXTVAL
            , '1'
            , 'abcd1111'       
            , 'ROLE_USER'
        );